name: ${project.name}
version: ${project.version}
main: me.sizzlemcgrizzle.blueprints.BlueprintsPlugin
author: sizzlemcgrizzle
api-version: 1.13
description: Place "blueprint" blocks to build schematics!
softdepend: [CLClans, WorldEdit, WorldGuard, Essentials, Vault]
permissions:
  blueprints.create.color:
    default: op
  blueprints.admin:
    default: op
commands:
  blueprints:
    description: Command parent for blueprints

