name: ${project.name}
version: ${project.version}
main: me.sizzlemcgrizzle.superblocks.SuperBlocksPlugin
author: sizzlemcgrizzle
api-version: 1.13
description: Modified uses of certain blocks
permissions:
commands:
