# ------------------------------------------------------------------------------------------- #
#                                                                                             #
# Welcome to the settings file for Blueprints.                                                #
# For documentation, visit: https://github.com/SizzleMcGrizzle/Blueprints/wiki/settings.yml   #
#                                                                                             #
# ------------------------------------------------------------------------------------------- #

Play_Sounds: true
Use_Economy: true

Block:
  Bossbar_Duration: 60
  Show_Error_Preview: true
  Error_Block: RED_CONCRETE
  Block_Timeout: 5
  No_Place_Outside_Claims: true
  No_Place_Block_In_Way: true
  No_Place_Admin_Claim: true
  Ignore_Blocks:
    - GRASS
    - WATER
    - SEAGRASS
    - TALL_SEAGRASS
    - TALL_GRASS
    - SNOW
    - KELP_PLANT
    - KELP
    - POPPY
    - OAK_SAPLING
    - SPRUCE_SAPLING
    - BIRCH_SAPLING
    - DARK_OAK_SAPLING
    - JUNGLE_SAPLING
    - ACACIA_SAPLING
    - DANDELION
    - BLUE_ORCHID
    - VINE
    - WALL_TORCH
    - SUNFLOWER
    - ALLIUM
    - AZURE_BLUET
    - ORANGE_TULIP
    - PINK_TULIP
    - RED_TULIP
    - WHITE_TULIP
    - OXEYE_DAISY
    - CORNFLOWER
    - RED_MUSHROOM
    - BROWN_MUSHROOM
    - FERN
    - TORCH
    - DEAD_BUSH

Messages:
  Message_Prefix: "&8[&3Blueprints&8] "
  Reload_Success: "&aBlueprints configuration has been successfully reloaded."
  Build_Success: "&bYour blueprint has been built!"
  Player_Not_Trusted: "&cYou must place your blueprint in a claim you are trusted in!"
  Show_Error_True_Message: "&cThis blueprint cannot be placed here."
  Show_Error_False_Message: "&cYour blueprint cannot be built here because there are blocks in the way."
  Placement_Denied: "&eYou have cancelled the placement and your item has been returned."
  Is_Conversing: "&ePlease confirm/deny your existing placement before making a new one!"
  Invalid_Schematic: "&cThis blueprint is not valid! Please contact an administrator immediately!"
  Above_Y_255: "&cPart of your blueprint will be placed above Y 255, so your placement has been cancelled."

Player_Blueprint:
  Player_Blueprint_Price_Multiplier: 0.5
  Player_Blueprint_Limits:
    - blueprints.placement.5
    - blueprints.placement.10
    - blueprints.placement.-1
  Disabled_Materials:
    - WATER
    - LAVA
    - RED_MUSHROOM_BLOCK
    - BROWN_MUSHROOM_BLOCK
    - SAND
    - GRAVEL
    - RED_SAND
  Player_Blueprint_Max_Size: 32768
  Player_Blueprint_Material_Price_Multiplier:
    BARRIER: 1

Log_Lag_Over_Milis: 100
Debug: [ ]
Version: 1